# [target.aarch64-unknown-linux-gnu]
# linker = "aarch64-unknown-linux-gnu-gcc"
# rustflags = ["-C", "linker=aarch64-unknown-linux-gnu-gcc"]

# [env]
# CC_aarch64_unknown_linux_gnu = "aarch64-unknown-linux-gnu-gcc"

# [build]
# target = "aarch64-unknown-linux-gnu"
# 
[build]
target = "aarch64-linux-android"
