[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.6"
crypto = { path = "../crypto" }
config = { path = "../config" }
bincode = { path = "../bincode" }
zil_errors = { path = "../zil_errors" }
serde = { version = "1.0.204", features = ["derive"] }
sha2 = "0.10.8"
hex = "0.4.3"
ethers = "2.0.14"
rand_chacha = "0.3.1"
rand = "0.8.5"
k256 = "0.13.3"
tiny-hderive = "0.3.0"

[build-dependencies]
prost-build = "0.12.6"
