[package]
name = "background"
version = "0.1.0"
edition = "2021"

[dependencies]
zil_errors = { path = "../zil_errors" }
session = { path = "../session" }
wallet = { path = "../wallet" }
storage = { path = "../storage" }
config = { path = "../config" }
settings = { path = "../settings" }
crypto = { path = "../crypto" }
proto = { path = "../proto" }
cipher = { path = "../cipher" }
bip39 = "2.0.0"
rand = "0.8.5"
hex = "0.4.3"
